// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"database/sql"
)

const countAuditLogs = `-- name: CountAuditLogs :one
2;

SELECT COUNT(*) FROM audit_l
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (user_id, action, details)
VALUES (?1, ?2, ?3)
`

type CreateAuditLogParams struct {
	UserID  sql.NullInt64  `json:"user_id"`
	Action  string         `json:"action"`
	Details sql.NullString `json:"details"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog, arg.UserID, arg.Action, arg.Details)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, a.action, a.details, a.created_at,
       COALESCE(u.login, '—') AS user_login
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
ORDER BY a.created_at DESC
LIMIT ?1 OFFSET
`

type ListAuditLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Action    string         `json:"action"`
	Details   sql.NullString `json:"details"`
	CreatedAt sql.NullString `json:"created_at"`
	UserLogin string         `json:"user_login"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
