// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package store

import (
	"context"
	"database/sql"
)

const clearClientAlert = `-- name: ClearClientAlert :exec
UPDATE clients SET alert_note = '' WHERE id = ?1
`

func (q *Queries) ClearClientAlert(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearClientAlert, id)
	return err
}

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, surname, email, phone, comment, alert_note)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, name, surname, email, phone, comment, alert_note, rfid_tag, created_at
`

type CreateClientParams struct {
	Name      string         `json:"name"`
	Surname   string         `json:"surname"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Comment   sql.NullString `json:"comment"`
	AlertNote string         `json:"alert_note"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Phone,
		arg.Comment,
		arg.AlertNote,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Comment,
		&i.AlertNote,
		&i.RfidTag,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = ?1
`

func (q *Queries) DeleteClient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, surname, email, phone, comment, alert_note, rfid_tag, created_at
FROM clients
WHERE id = ?1
`

func (q *Queries) GetClient(ctx context.Context, id int64) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Comment,
		&i.AlertNote,
		&i.RfidTag,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByRFID = `-- name: GetClientByRFID :one
SELECT id, name, surname, email, phone, comment, alert_note, rfid_tag, created_at
FROM clients
WHERE rfid_tag = ?1
`

func (q *Queries) GetClientByRFID(ctx context.Context, rfidTag sql.NullString) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByRFID, rfidTag)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Comment,
		&i.AlertNote,
		&i.RfidTag,
		&i.CreatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, surname, email, phone, comment, alert_note, rfid_tag, created_at
FROM clients
ORDER BY surname, name
LIMIT ?1 OFFSET ?2
`

type ListClientsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Comment,
			&i.AlertNote,
			&i.RfidTag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, name, surname, email, phone, comment, alert_note, rfid_tag, created_at
FROM clients
WHERE (name || ' ' || surname) LIKE '%' || ?1 || '%'
   OR phone LIKE '%' || ?1 || '%'
   OR email LIKE '%' || ?1 || '%'
ORDER BY surname, name
LIMIT 50
`

func (q *Queries) SearchClients(ctx context.Context, query sql.NullString) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClients, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Comment,
			&i.AlertNote,
			&i.RfidTag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = ?2, surname = ?3, email = ?4, phone = ?5, comment = ?6, alert_note = ?7
WHERE id = ?1
RETURNING id, name, surname, email, phone, comment, alert_note, rfid_tag, created_at
`

type UpdateClientParams struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Surname   string         `json:"surname"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Comment   sql.NullString `json:"comment"`
	AlertNote string         `json:"alert_note"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Phone,
		arg.Comment,
		arg.AlertNote,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Comment,
		&i.AlertNote,
		&i.RfidTag,
		&i.CreatedAt,
	)
	return i, err
}

const updateClientRFID = `-- name: UpdateClientRFID :exec
UPDATE clients SET rfid_tag = ?2 WHERE id = ?1
`

type UpdateClientRFIDParams struct {
	ID      int64          `json:"id"`
	RfidTag sql.NullString `json:"rfid_tag"`
}

func (q *Queries) UpdateClientRFID(ctx context.Context, arg UpdateClientRFIDParams) error {
	_, err := q.db.ExecContext(ctx, updateClientRFID, arg.ID, arg.RfidTag)
	return err
}
