// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package store

import (
	"context"
	"database/sql"
)

const countActiveClients = `-- name: CountActiveClients :one
SELECT COUNT(*) FROM clients
`

func (q *Queries) CountActiveClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiringMemberships = `-- name: CountExpiringMemberships :one
SELECT COUNT(*) FROM memberships WHERE is_active = 1 AND ends_at BETWEEN date('now') AND date('now', '+7 days')
`

func (q *Queries) CountExpiringMemberships(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpiringMemberships)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listExpiringMemberships = `-- name: ListExpiringMemberships :many
SELECT m.id, m.ends_at, c.id AS client_id, c.name AS client_name, c.surname AS client_surname,
       mt.name AS type_name
FROM memberships m
JOIN clients c ON c.id = m.client_id
JOIN membership_types mt ON mt.id = m.type_id
WHERE m.is_active = 1 AND m.ends_at BETWEEN date('now') AND date('now', '+7 days')
ORDER BY m.ends_at
`

type ListExpiringMembershipsRow struct {
	ID            int64  `json:"id"`
	EndsAt        string `json:"ends_at"`
	ClientID      int64  `json:"client_id"`
	ClientName    string `json:"client_name"`
	ClientSurname string `json:"client_surname"`
	TypeName      string `json:"type_name"`
}

func (q *Queries) ListExpiringMemberships(ctx context.Context) ([]ListExpiringMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringMembershipsRow{}
	for rows.Next() {
		var i ListExpiringMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.EndsAt,
			&i.ClientID,
			&i.ClientName,
			&i.ClientSurname,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEntries = `-- name: ListRecentEntries :many
SELECT e.id, e.method, e.created_at,
       c.id AS client_id, c.name AS client_name, c.surname AS client_surname
FROM entries e
JOIN clients c ON c.id = e.client_id
WHERE e.created_at >= date('now')
ORDER BY e.created_at DESC
LIMIT 10
`

type ListRecentEntriesRow struct {
	ID            int64          `json:"id"`
	Method        sql.NullString `json:"method"`
	CreatedAt     sql.NullString `json:"created_at"`
	ClientID      int64          `json:"client_id"`
	ClientName    string         `json:"client_name"`
	ClientSurname string         `json:"client_surname"`
}

func (q *Queries) ListRecentEntries(ctx context.Context) ([]ListRecentEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentEntriesRow{}
	for rows.Next() {
		var i ListRecentEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.CreatedAt,
			&i.ClientID,
			&i.ClientName,
			&i.ClientSurname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
