// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package store

import (
	"context"
	"database/sql"
)

const countEntriesByClient = `-- name: CountEntriesByClient :one
SELECT COUNT(*) FROM entries WHERE client_id = ?1
`

func (q *Queries) CountEntriesByClient(ctx context.Context, clientID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntriesByClient, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesToday = `-- name: CountEntriesToday :one
SELECT COUNT(*) FROM entries WHERE created_at >= date('now')
`

func (q *Queries) CountEntriesToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntriesToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (client_id, recorded_by, method)
VALUES (?1, ?2, ?3)
RETURNING id, client_id, recorded_by, method, created_at
`

type CreateEntryParams struct {
	ClientID   int64          `json:"client_id"`
	RecordedBy sql.NullInt64  `json:"recorded_by"`
	Method     sql.NullString `json:"method"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.ClientID, arg.RecordedBy, arg.Method)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RecordedBy,
		&i.Method,
		&i.CreatedAt,
	)
	return i, err
}

const getLastEntryByClient = `-- name: GetLastEntryByClient :one
SELECT id, created_at FROM entries
WHERE client_id = ?1
ORDER BY created_at DESC
LIMIT 1
`

type GetLastEntryByClientRow struct {
	ID        int64          `json:"id"`
	CreatedAt sql.NullString `json:"created_at"`
}

func (q *Queries) GetLastEntryByClient(ctx context.Context, clientID int64) (GetLastEntryByClientRow, error) {
	row := q.db.QueryRowContext(ctx, getLastEntryByClient, clientID)
	var i GetLastEntryByClientRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listEntriesByClient = `-- name: ListEntriesByClient :many
SELECT e.id, e.client_id, e.recorded_by, e.method, e.created_at,
       COALESCE(u.name, '') AS recorded_by_name
FROM entries e
LEFT JOIN users u ON u.id = e.recorded_by
WHERE e.client_id = ?1
ORDER BY e.created_at DESC
LIMIT ?2
`

type ListEntriesByClientParams struct {
	ClientID int64 `json:"client_id"`
	Limit    int64 `json:"limit"`
}

type ListEntriesByClientRow struct {
	ID             int64          `json:"id"`
	ClientID       int64          `json:"client_id"`
	RecordedBy     sql.NullInt64  `json:"recorded_by"`
	Method         sql.NullString `json:"method"`
	CreatedAt      sql.NullString `json:"created_at"`
	RecordedByName string         `json:"recorded_by_name"`
}

func (q *Queries) ListEntriesByClient(ctx context.Context, arg ListEntriesByClientParams) ([]ListEntriesByClientRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByClient, arg.ClientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesByClientRow{}
	for rows.Next() {
		var i ListEntriesByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.RecordedBy,
			&i.Method,
			&i.CreatedAt,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesToday = `-- name: ListEntriesToday :many
SELECT e.id, e.client_id, e.method, e.created_at,
       c.name AS client_name, c.surname AS client_surname
FROM entries e
JOIN clients c ON c.id = e.client_id
WHERE e.created_at >= date('now')
ORDER BY e.created_at DESC
`

type ListEntriesTodayRow struct {
	ID            int64          `json:"id"`
	ClientID      int64          `json:"client_id"`
	Method        sql.NullString `json:"method"`
	CreatedAt     sql.NullString `json:"created_at"`
	ClientName    string         `json:"client_name"`
	ClientSurname string         `json:"client_surname"`
}

func (q *Queries) ListEntriesToday(ctx context.Context) ([]ListEntriesTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesTodayRow{}
	for rows.Next() {
		var i ListEntriesTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Method,
			&i.CreatedAt,
			&i.ClientName,
			&i.ClientSurname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
