// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS ok
`

func (q *Queries) HealthCheck(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, healthCheck)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}
