// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership_types.sql

package store

import (
	"context"
	"database/sql"
)

const countMembershipTypes = `-- name: CountMembershipTypes :one
SELECT COUNT(*) FROM membership_types
`

func (q *Queries) CountMembershipTypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembershipTypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembershipType = `-- name: CreateMembershipType :one
INSERT INTO membership_types (name, description, duration_value, duration_unit, is_contract, price, is_active, max_freeze_days)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, name, description, duration_value, duration_unit, is_contract, price, is_active, max_freeze_days, created_at
`

type CreateMembershipTypeParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	DurationValue int64          `json:"duration_value"`
	DurationUnit  string         `json:"duration_unit"`
	IsContract    sql.NullInt64  `json:"is_contract"`
	Price         float64        `json:"price"`
	IsActive      sql.NullInt64  `json:"is_active"`
	MaxFreezeDays int64          `json:"max_freeze_days"`
}

func (q *Queries) CreateMembershipType(ctx context.Context, arg CreateMembershipTypeParams) (MembershipType, error) {
	row := q.db.QueryRowContext(ctx, createMembershipType,
		arg.Name,
		arg.Description,
		arg.DurationValue,
		arg.DurationUnit,
		arg.IsContract,
		arg.Price,
		arg.IsActive,
		arg.MaxFreezeDays,
	)
	var i MembershipType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationValue,
		&i.DurationUnit,
		&i.IsContract,
		&i.Price,
		&i.IsActive,
		&i.MaxFreezeDays,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembershipType = `-- name: DeleteMembershipType :exec
DELETE FROM membership_types WHERE id = ?1
`

func (q *Queries) DeleteMembershipType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMembershipType, id)
	return err
}

const getMembershipType = `-- name: GetMembershipType :one
SELECT id, name, description, duration_value, duration_unit, is_contract, price, is_active, max_freeze_days, created_at FROM membership_types WHERE id = ?1
`

func (q *Queries) GetMembershipType(ctx context.Context, id int64) (MembershipType, error) {
	row := q.db.QueryRowContext(ctx, getMembershipType, id)
	var i MembershipType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationValue,
		&i.DurationUnit,
		&i.IsContract,
		&i.Price,
		&i.IsActive,
		&i.MaxFreezeDays,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveMembershipTypes = `-- name: ListActiveMembershipTypes :many
SELECT id, name, description, duration_value, duration_unit, is_contract, price, max_freeze_days
FROM membership_types
WHERE is_active = 1
ORDER BY name
`

type ListActiveMembershipTypesRow struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	DurationValue int64          `json:"duration_value"`
	DurationUnit  string         `json:"duration_unit"`
	IsContract    sql.NullInt64  `json:"is_contract"`
	Price         float64        `json:"price"`
	MaxFreezeDays int64          `json:"max_freeze_days"`
}

func (q *Queries) ListActiveMembershipTypes(ctx context.Context) ([]ListActiveMembershipTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMembershipTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMembershipTypesRow{}
	for rows.Next() {
		var i ListActiveMembershipTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationValue,
			&i.DurationUnit,
			&i.IsContract,
			&i.Price,
			&i.MaxFreezeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipTypes = `-- name: ListMembershipTypes :many
SELECT id, name, description, duration_value, duration_unit, is_contract, price, is_active, max_freeze_days, created_at
FROM membership_types
ORDER BY is_active DESC, name
`

func (q *Queries) ListMembershipTypes(ctx context.Context) ([]MembershipType, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipType{}
	for rows.Next() {
		var i MembershipType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationValue,
			&i.DurationUnit,
			&i.IsContract,
			&i.Price,
			&i.IsActive,
			&i.MaxFreezeDays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipType = `-- name: UpdateMembershipType :one
UPDATE membership_types
SET name = ?2, description = ?3, duration_value = ?4, duration_unit = ?5, is_contract = ?6, price = ?7, is_active = ?8, max_freeze_days = ?9
WHERE id = ?1
RETURNING id, name, description, duration_value, duration_unit, is_contract, price, is_active, max_freeze_days, created_at
`

type UpdateMembershipTypeParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	DurationValue int64          `json:"duration_value"`
	DurationUnit  string         `json:"duration_unit"`
	IsContract    sql.NullInt64  `json:"is_contract"`
	Price         float64        `json:"price"`
	IsActive      sql.NullInt64  `json:"is_active"`
	MaxFreezeDays int64          `json:"max_freeze_days"`
}

func (q *Queries) UpdateMembershipType(ctx context.Context, arg UpdateMembershipTypeParams) (MembershipType, error) {
	row := q.db.QueryRowContext(ctx, updateMembershipType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DurationValue,
		arg.DurationUnit,
		arg.IsContract,
		arg.Price,
		arg.IsActive,
		arg.MaxFreezeDays,
	)
	var i MembershipType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationValue,
		&i.DurationUnit,
		&i.IsContract,
		&i.Price,
		&i.IsActive,
		&i.MaxFreezeDays,
		&i.CreatedAt,
	)
	return i, err
}
