// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package store

import (
	"context"
	"database/sql"
)

const countActiveMemberships = `-- name: CountActiveMemberships :one
SELECT COUNT(*) FROM memberships WHERE is_active = 1 AND ends_at >= date('now')
`

func (q *Queries) CountActiveMemberships(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMemberships)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiredMemberships = `-- name: CountExpiredMemberships :one
SELECT COUNT(*) FROM memberships WHERE is_active = 1 AND ends_at < date('now')
`

func (q *Queries) CountExpiredMemberships(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpiredMemberships)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (client_id, type_id, starts_at, ends_at, is_active)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, client_id, type_id, starts_at, ends_at, is_active, frozen_at, frozen_until, total_frozen_days, created_at
`

type CreateMembershipParams struct {
	ClientID int64         `json:"client_id"`
	TypeID   int64         `json:"type_id"`
	StartsAt string        `json:"starts_at"`
	EndsAt   string        `json:"ends_at"`
	IsActive sql.NullInt64 `json:"is_active"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, createMembership,
		arg.ClientID,
		arg.TypeID,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TypeID,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.FrozenAt,
		&i.FrozenUntil,
		&i.TotalFrozenDays,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateMembership = `-- name: DeactivateMembership :exec
UPDATE memberships SET is_active = 0, frozen_at = NULL WHERE id = ?1
`

func (q *Queries) DeactivateMembership(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateMembership, id)
	return err
}

const freezeMembership = `-- name: FreezeMembership :exec
UPDATE memberships
SET frozen_at = ?2,
    frozen_until = ?3
WHERE id = ?1
`

type FreezeMembershipParams struct {
	ID          int64          `json:"id"`
	FreezeFrom  sql.NullString `json:"freeze_from"`
	FreezeUntil sql.NullString `json:"freeze_until"`
}

func (q *Queries) FreezeMembership(ctx context.Context, arg FreezeMembershipParams) error {
	_, err := q.db.ExecContext(ctx, freezeMembership, arg.ID, arg.FreezeFrom, arg.FreezeUntil)
	return err
}

const getActiveMembership = `-- name: GetActiveMembership :one
SELECT m.id, m.client_id, m.type_id, m.starts_at, m.ends_at, m.is_active,
       m.frozen_at, m.frozen_until, m.total_frozen_days,
       mt.name AS type_name
FROM memberships m
JOIN membership_types mt ON mt.id = m.type_id
WHERE m.client_id = ?1 AND m.is_active = 1 AND m.ends_at >= date('now')
LIMIT 1
`

type GetActiveMembershipRow struct {
	ID              int64          `json:"id"`
	ClientID        int64          `json:"client_id"`
	TypeID          int64          `json:"type_id"`
	StartsAt        string         `json:"starts_at"`
	EndsAt          string         `json:"ends_at"`
	IsActive        sql.NullInt64  `json:"is_active"`
	FrozenAt        sql.NullString `json:"frozen_at"`
	FrozenUntil     sql.NullString `json:"frozen_until"`
	TotalFrozenDays int64          `json:"total_frozen_days"`
	TypeName        string         `json:"type_name"`
}

func (q *Queries) GetActiveMembership(ctx context.Context, clientID int64) (GetActiveMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveMembership, clientID)
	var i GetActiveMembershipRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TypeID,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.FrozenAt,
		&i.FrozenUntil,
		&i.TotalFrozenDays,
		&i.TypeName,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT m.id, m.client_id, m.type_id, m.starts_at, m.ends_at, m.is_active, m.frozen_at, m.frozen_until, m.total_frozen_days, m.created_at, mt.name AS type_name, mt.price AS type_price, mt.max_freeze_days
FROM memberships m
JOIN membership_types mt ON mt.id = m.type_id
WHERE m.id = ?1
`

type GetMembershipRow struct {
	ID              int64          `json:"id"`
	ClientID        int64          `json:"client_id"`
	TypeID          int64          `json:"type_id"`
	StartsAt        string         `json:"starts_at"`
	EndsAt          string         `json:"ends_at"`
	IsActive        sql.NullInt64  `json:"is_active"`
	FrozenAt        sql.NullString `json:"frozen_at"`
	FrozenUntil     sql.NullString `json:"frozen_until"`
	TotalFrozenDays int64          `json:"total_frozen_days"`
	CreatedAt       sql.NullString `json:"created_at"`
	TypeName        string         `json:"type_name"`
	TypePrice       float64        `json:"type_price"`
	MaxFreezeDays   int64          `json:"max_freeze_days"`
}

func (q *Queries) GetMembership(ctx context.Context, id int64) (GetMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getMembership, id)
	var i GetMembershipRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TypeID,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.FrozenAt,
		&i.FrozenUntil,
		&i.TotalFrozenDays,
		&i.CreatedAt,
		&i.TypeName,
		&i.TypePrice,
		&i.MaxFreezeDays,
	)
	return i, err
}

const hasOverlappingMembership = `-- name: HasOverlappingMembership :one
SELECT COUNT(*) > 0 AS has_overlap
FROM memberships
WHERE client_id = ?1
  AND is_active = 1
  AND starts_at <= ?2
  AND ends_at >= ?3
`

type HasOverlappingMembershipParams struct {
	ClientID    int64  `json:"client_id"`
	NewEndsAt   string `json:"new_ends_at"`
	NewStartsAt string `json:"new_starts_at"`
}

func (q *Queries) HasOverlappingMembership(ctx context.Context, arg HasOverlappingMembershipParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasOverlappingMembership, arg.ClientID, arg.NewEndsAt, arg.NewStartsAt)
	var has_overlap bool
	err := row.Scan(&has_overlap)
	return has_overlap, err
}

const listMembershipsByClient = `-- name: ListMembershipsByClient :many
SELECT m.id, m.client_id, m.type_id, m.starts_at, m.ends_at, m.is_active,
       m.frozen_at, m.frozen_until, m.total_frozen_days, m.created_at,
       mt.name AS type_name, mt.price AS type_price, mt.max_freeze_days
FROM memberships m
JOIN membership_types mt ON mt.id = m.type_id
WHERE m.client_id = ?1
ORDER BY m.starts_at DESC
`

type ListMembershipsByClientRow struct {
	ID              int64          `json:"id"`
	ClientID        int64          `json:"client_id"`
	TypeID          int64          `json:"type_id"`
	StartsAt        string         `json:"starts_at"`
	EndsAt          string         `json:"ends_at"`
	IsActive        sql.NullInt64  `json:"is_active"`
	FrozenAt        sql.NullString `json:"frozen_at"`
	FrozenUntil     sql.NullString `json:"frozen_until"`
	TotalFrozenDays int64          `json:"total_frozen_days"`
	CreatedAt       sql.NullString `json:"created_at"`
	TypeName        string         `json:"type_name"`
	TypePrice       float64        `json:"type_price"`
	MaxFreezeDays   int64          `json:"max_freeze_days"`
}

func (q *Queries) ListMembershipsByClient(ctx context.Context, clientID int64) ([]ListMembershipsByClientRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByClientRow{}
	for rows.Next() {
		var i ListMembershipsByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TypeID,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.FrozenAt,
			&i.FrozenUntil,
			&i.TotalFrozenDays,
			&i.CreatedAt,
			&i.TypeName,
			&i.TypePrice,
			&i.MaxFreezeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfreezeMembership = `-- name: UnfreezeMembership :exec
UPDATE memberships
SET total_frozen_days = total_frozen_days + CAST(julianday(COALESCE(frozen_until, date('now'))) - julianday(frozen_at) AS INTEGER),
    ends_at = date(ends_at, '+' || CAST(julianday(COALESCE(frozen_until, date('now'))) - julianday(frozen_at) AS INTEGER) || ' days'),
    frozen_at = NULL,
    frozen_until = NULL
WHERE id = ?1 AND frozen_at IS NOT NULL
`

func (q *Queries) UnfreezeMembership(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unfreezeMembership, id)
	return err
}
