// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AuditLog struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Action    string         `json:"action"`
	Details   sql.NullString `json:"details"`
	CreatedAt sql.NullString `json:"created_at"`
}

type Client struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Surname   string         `json:"surname"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Comment   sql.NullString `json:"comment"`
	AlertNote string         `json:"alert_note"`
	RfidTag   sql.NullString `json:"rfid_tag"`
	CreatedAt sql.NullString `json:"created_at"`
}

type Entry struct {
	ID         int64          `json:"id"`
	ClientID   int64          `json:"client_id"`
	RecordedBy sql.NullInt64  `json:"recorded_by"`
	Method     sql.NullString `json:"method"`
	CreatedAt  sql.NullString `json:"created_at"`
}

type Membership struct {
	ID              int64          `json:"id"`
	ClientID        int64          `json:"client_id"`
	TypeID          int64          `json:"type_id"`
	StartsAt        string         `json:"starts_at"`
	EndsAt          string         `json:"ends_at"`
	IsActive        sql.NullInt64  `json:"is_active"`
	FrozenAt        sql.NullString `json:"frozen_at"`
	FrozenUntil     sql.NullString `json:"frozen_until"`
	TotalFrozenDays int64          `json:"total_frozen_days"`
	CreatedAt       sql.NullString `json:"created_at"`
}

type MembershipType struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	DurationValue int64          `json:"duration_value"`
	DurationUnit  string         `json:"duration_unit"`
	IsContract    sql.NullInt64  `json:"is_contract"`
	Price         float64        `json:"price"`
	IsActive      sql.NullInt64  `json:"is_active"`
	MaxFreezeDays int64          `json:"max_freeze_days"`
	CreatedAt     sql.NullString `json:"created_at"`
}

type Payment struct {
	ID           int64          `json:"id"`
	MembershipID int64          `json:"membership_id"`
	DueDate      string         `json:"due_date"`
	PaidAt       sql.NullString `json:"paid_at"`
	Amount       float64        `json:"amount"`
}

type User struct {
	ID           int64          `json:"id"`
	Login        string         `json:"login"`
	Name         string         `json:"name"`
	Surname      string         `json:"surname"`
	Role         string         `json:"role"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    sql.NullString `json:"created_at"`
}
