// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"
	"database/sql"
)

const countOverduePayments = `-- name: CountOverduePayments :one
SELECT COUNT(*) FROM payments WHERE paid_at IS NULL AND due_date < date('now')
`

func (q *Queries) CountOverduePayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOverduePayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnpaidPayments = `-- name: CountUnpaidPayments :one
SELECT COUNT(*) FROM payments WHERE paid_at IS NULL
`

func (q *Queries) CountUnpaidPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnpaidPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (membership_id, due_date, amount)
VALUES (?1, ?2, ?3)
RETURNING id, membership_id, due_date, paid_at, amount
`

type CreatePaymentParams struct {
	MembershipID int64   `json:"membership_id"`
	DueDate      string  `json:"due_date"`
	Amount       float64 `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.MembershipID, arg.DueDate, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.DueDate,
		&i.PaidAt,
		&i.Amount,
	)
	return i, err
}

const listOverduePayments = `-- name: ListOverduePayments :many
SELECT p.id, p.membership_id, p.due_date, p.amount,
       c.id AS client_id, c.name AS client_name, c.surname AS client_surname,
       mt.name AS type_name
FROM payments p
JOIN memberships m ON m.id = p.membership_id
JOIN clients c ON c.id = m.client_id
JOIN membership_types mt ON mt.id = m.type_id
WHERE p.paid_at IS NULL AND p.due_date < date('now')
ORDER BY p.due_date
`

type ListOverduePaymentsRow struct {
	ID            int64   `json:"id"`
	MembershipID  int64   `json:"membership_id"`
	DueDate       string  `json:"due_date"`
	Amount        float64 `json:"amount"`
	ClientID      int64   `json:"client_id"`
	ClientName    string  `json:"client_name"`
	ClientSurname string  `json:"client_surname"`
	TypeName      string  `json:"type_name"`
}

func (q *Queries) ListOverduePayments(ctx context.Context) ([]ListOverduePaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOverduePayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverduePaymentsRow{}
	for rows.Next() {
		var i ListOverduePaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.DueDate,
			&i.Amount,
			&i.ClientID,
			&i.ClientName,
			&i.ClientSurname,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByClient = `-- name: ListPaymentsByClient :many
SELECT p.id, p.membership_id, p.due_date, p.paid_at, p.amount,
       mt.name AS type_name
FROM payments p
JOIN memberships m ON m.id = p.membership_id
JOIN membership_types mt ON mt.id = m.type_id
WHERE m.client_id = ?1
ORDER BY p.due_date DESC
`

type ListPaymentsByClientRow struct {
	ID           int64          `json:"id"`
	MembershipID int64          `json:"membership_id"`
	DueDate      string         `json:"due_date"`
	PaidAt       sql.NullString `json:"paid_at"`
	Amount       float64        `json:"amount"`
	TypeName     string         `json:"type_name"`
}

func (q *Queries) ListPaymentsByClient(ctx context.Context, clientID int64) ([]ListPaymentsByClientRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByClientRow{}
	for rows.Next() {
		var i ListPaymentsByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.DueDate,
			&i.PaidAt,
			&i.Amount,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByMembership = `-- name: ListPaymentsByMembership :many
SELECT id, membership_id, due_date, paid_at, amount
FROM payments
WHERE membership_id = ?1
ORDER BY due_date DESC
`

func (q *Queries) ListPaymentsByMembership(ctx context.Context, membershipID int64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.DueDate,
			&i.PaidAt,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentPaid = `-- name: MarkPaymentPaid :exec
UPDATE payments SET paid_at = datetime('now') WHERE id = ?1
`

func (q *Queries) MarkPaymentPaid(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPaymentPaid, id)
	return err
}
